title: "ðŸ§  ML Researcher Foundations"
description: "Your Complete Journey from Zero to ML Research â€¢ By Gaurav Goswami"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
